# Copyright (c) 2026 Flick. All Rights Reserved.

services:
  # API Service
  flick-api:
    image: dellixou/flick-api:${VERSION:-latest}
    build:
      context: ./
      args:
        VERSION: ${VERSION:-selfbuild}
        COMMIT: ${COMMIT:-}
        BUILD_DATE: ${BUILD_DATE:-}
    container_name: flick-api
    restart: unless-stopped
    ports:
      - "15702:15702/udp"
      - "15702:15702/tcp"
    volumes:
      - ./certificates:/app/certificates:ro
    networks:
      - flick

  # Web Service
  flick-web:
    image: dellixou/flick-web:${VERSION:-latest}
    build:
      context: ./web/
    container_name: flick-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - flick-api
    networks:
      - flick

networks:
  flick:
    driver: bridge
