// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_authorizations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDeviceAuthorization = `-- name: ApproveDeviceAuthorization :one
UPDATE device_authorizations
SET status = 'approved', user_id = $2, session_token = $3
WHERE user_code = $1 AND status = 'pending'
RETURNING device_code, user_code, status, user_id, session_token, expires_at, created_at
`

type ApproveDeviceAuthorizationParams struct {
	UserCode     string      `json:"user_code"`
	UserID       pgtype.UUID `json:"user_id"`
	SessionToken *string     `json:"session_token"`
}

func (q *Queries) ApproveDeviceAuthorization(ctx context.Context, arg ApproveDeviceAuthorizationParams) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, approveDeviceAuthorization, arg.UserCode, arg.UserID, arg.SessionToken)
	var i DeviceAuthorization
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDeviceAuthorization = `-- name: CreateDeviceAuthorization :one
INSERT INTO device_authorizations (device_code, user_code, expires_at)
VALUES ($1, $2, $3)
RETURNING device_code, user_code, status, user_id, session_token, expires_at, created_at
`

type CreateDeviceAuthorizationParams struct {
	DeviceCode string             `json:"device_code"`
	UserCode   string             `json:"user_code"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDeviceAuthorization(ctx context.Context, arg CreateDeviceAuthorizationParams) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, createDeviceAuthorization, arg.DeviceCode, arg.UserCode, arg.ExpiresAt)
	var i DeviceAuthorization
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredDeviceAuthorizations = `-- name: DeleteExpiredDeviceAuthorizations :exec
DELETE FROM device_authorizations
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredDeviceAuthorizations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredDeviceAuthorizations)
	return err
}

const denyDeviceAuthorization = `-- name: DenyDeviceAuthorization :one
UPDATE device_authorizations
SET status = 'denied'
WHERE user_code = $1 AND status = 'pending'
RETURNING device_code, user_code, status, user_id, session_token, expires_at, created_at
`

func (q *Queries) DenyDeviceAuthorization(ctx context.Context, userCode string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, denyDeviceAuthorization, userCode)
	var i DeviceAuthorization
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceAuthorizationByDeviceCode = `-- name: GetDeviceAuthorizationByDeviceCode :one
SELECT device_code, user_code, status, user_id, session_token, expires_at, created_at FROM device_authorizations
WHERE device_code = $1 AND expires_at > now()
`

func (q *Queries) GetDeviceAuthorizationByDeviceCode(ctx context.Context, deviceCode string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getDeviceAuthorizationByDeviceCode, deviceCode)
	var i DeviceAuthorization
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceAuthorizationByUserCode = `-- name: GetDeviceAuthorizationByUserCode :one
SELECT device_code, user_code, status, user_id, session_token, expires_at, created_at FROM device_authorizations
WHERE user_code = $1 AND expires_at > now()
`

func (q *Queries) GetDeviceAuthorizationByUserCode(ctx context.Context, userCode string) (DeviceAuthorization, error) {
	row := q.db.QueryRow(ctx, getDeviceAuthorizationByUserCode, userCode)
	var i DeviceAuthorization
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.UserID,
		&i.SessionToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
