// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_uploads.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupUpload = `-- name: CreateGroupUpload :one
INSERT INTO group_uploads (group_id, folder_id, code, uploader_id)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, folder_id, code, uploader_id, created_at
`

type CreateGroupUploadParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	FolderID   pgtype.UUID `json:"folder_id"`
	Code       string      `json:"code"`
	UploaderID pgtype.UUID `json:"uploader_id"`
}

func (q *Queries) CreateGroupUpload(ctx context.Context, arg CreateGroupUploadParams) (GroupUpload, error) {
	row := q.db.QueryRow(ctx, createGroupUpload,
		arg.GroupID,
		arg.FolderID,
		arg.Code,
		arg.UploaderID,
	)
	var i GroupUpload
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FolderID,
		&i.Code,
		&i.UploaderID,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupUploadsByFolder = `-- name: ListGroupUploadsByFolder :many
SELECT gu.id, gu.code, gu.uploader_id, u.username AS uploader_username, gu.created_at
FROM group_uploads gu
JOIN users u ON u.id = gu.uploader_id
WHERE gu.group_id = $1 AND gu.folder_id IS NOT DISTINCT FROM $2
ORDER BY gu.created_at DESC
`

type ListGroupUploadsByFolderParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

type ListGroupUploadsByFolderRow struct {
	ID               pgtype.UUID        `json:"id"`
	Code             string             `json:"code"`
	UploaderID       pgtype.UUID        `json:"uploader_id"`
	UploaderUsername string             `json:"uploader_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGroupUploadsByFolder(ctx context.Context, arg ListGroupUploadsByFolderParams) ([]ListGroupUploadsByFolderRow, error) {
	rows, err := q.db.Query(ctx, listGroupUploadsByFolder, arg.GroupID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupUploadsByFolderRow
	for rows.Next() {
		var i ListGroupUploadsByFolderRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.UploaderID,
			&i.UploaderUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
