// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_folders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupFolder = `-- name: CreateGroupFolder :one
INSERT INTO group_folders (group_id, parent_id, name)
VALUES ($1, $2, $3)
RETURNING id, group_id, parent_id, name, created_at
`

type CreateGroupFolderParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateGroupFolder(ctx context.Context, arg CreateGroupFolderParams) (GroupFolder, error) {
	row := q.db.QueryRow(ctx, createGroupFolder, arg.GroupID, arg.ParentID, arg.Name)
	var i GroupFolder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroupFolder = `-- name: DeleteGroupFolder :exec
DELETE FROM group_folders
WHERE id = $1
`

func (q *Queries) DeleteGroupFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupFolder, id)
	return err
}

const getGroupFolderByID = `-- name: GetGroupFolderByID :one
SELECT id, group_id, parent_id, name, created_at FROM group_folders
WHERE id = $1
`

func (q *Queries) GetGroupFolderByID(ctx context.Context, id pgtype.UUID) (GroupFolder, error) {
	row := q.db.QueryRow(ctx, getGroupFolderByID, id)
	var i GroupFolder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupFoldersByParent = `-- name: ListGroupFoldersByParent :many
SELECT id, group_id, parent_id, name, created_at FROM group_folders
WHERE group_id = $1 AND parent_id IS NOT DISTINCT FROM $2
ORDER BY name
`

type ListGroupFoldersByParentParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListGroupFoldersByParent(ctx context.Context, arg ListGroupFoldersByParentParams) ([]GroupFolder, error) {
	rows, err := q.db.Query(ctx, listGroupFoldersByParent, arg.GroupID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupFolder
	for rows.Next() {
		var i GroupFolder
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
