#!/usr/bin/env bash
set -euo pipefail

VERSION="${VERSION:?VERSION is required (e.g. v1.2.3)}"
BASE_URL="${RELEASE_BASE_URL:-https://apt.d3l.tech/releases}"
OUT="${1:-Formula/flick.rb}"

sha() { grep " ${1}\$" build/bin/checksums.txt | cut -d' ' -f1; }
SHA_ARM64="$(sha flick-darwin-arm64)"
SHA_AMD64="$(sha flick-darwin-amd64)"
PLAIN_VERSION="${VERSION#v}"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" << EOF
# Generated by scripts/gen-formula.sh — do not edit by hand.
class Flick < Formula
  desc "Frictionless file transfer CLI. Share files with a short code."
  homepage "https://flick.d3l.tech"
  version "$PLAIN_VERSION"

  on_macos do
    on_arm do
      url "$BASE_URL/$VERSION/flick-darwin-arm64"
      sha256 "$SHA_ARM64"

      def install
        bin.install "flick-darwin-arm64" => "flick"
      end
    end

    on_intel do
      url "$BASE_URL/$VERSION/flick-darwin-amd64"
      sha256 "$SHA_AMD64"

      def install
        bin.install "flick-darwin-amd64" => "flick"
      end
    end
  end

  test do
    system "#{bin}/flick", "--version"
  end
end
EOF

echo "Wrote $OUT (version=$PLAIN_VERSION)"
